[build]
  command = "npm run build"
  functions = "functions"
  publish = "build"

[dev]
  command = "vite dev"

[functions]
  directory = "netlify/functions"

[context.production]
  environment = { NODE_ENV = "16.14.0" }